-- MySQL Script generated by MySQL Workbench
-- Mon Feb 11 15:58:05 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_exemplotabd
-- -----------------------------------------------------
-- Data:11/02/2019
-- Desenvolvedor: Eduardo Rafael 
-- Descrição: Banco de Dados para demonstrar os fundamentos 
-- da UC Tópicos Avançados de Banco de Dados.
-- 

-- -----------------------------------------------------
-- Schema bd_exemplotabd
--
-- Data:11/02/2019
-- Desenvolvedor: Eduardo Rafael 
-- Descrição: Banco de Dados para demonstrar os fundamentos 
-- da UC Tópicos Avançados de Banco de Dados.
-- 
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_exemplotabd` DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ;
USE `bd_exemplotabd` ;

-- -----------------------------------------------------
-- Table `bd_exemplotabd`.`setores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_exemplotabd`.`setores` (
  `id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Código de cada setor (único).',
  `nome` VARCHAR(20) NOT NULL COMMENT 'Nome do setor.',
  `descricao` TEXT NULL COMMENT 'Descrição informando o que é desenvolvido no setor.',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Tabela que armazena os setores da empresa.';


-- -----------------------------------------------------
-- Table `bd_exemplotabd`.`funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_exemplotabd`.`funcionarios` (
  `matricula` INT UNSIGNED ZEROFILL NOT NULL AUTO_INCREMENT COMMENT 'Matricula de cada funcionário gerada pelo sistema (único).',
  `nome` VARCHAR(50) NOT NULL COMMENT 'Nome completo do funcionário.',
  `dt_nasc` DATE NOT NULL COMMENT 'Data de nascimento.',
  `dt_adm` DATE NOT NULL COMMENT 'Data de Admissão.',
  `salario` DECIMAL(6,2) UNSIGNED NULL COMMENT 'Salário do funcionário.',
  `descricao` TEXT NULL COMMENT 'Descrição do perfil do funcionário.',
  `setores_id` TINYINT UNSIGNED NOT NULL COMMENT 'Identifica o setor que o funcionário trabalha.',
  PRIMARY KEY (`matricula`),
  INDEX `fk_funcionarios_setores_idx` (`setores_id`),
  CONSTRAINT `fk_funcionarios_setores`
    FOREIGN KEY (`setores_id`)
    REFERENCES `bd_exemplotabd`.`setores` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Tabela onde são cadastradas todos os funcionários da empresa. ';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
